### ISSUE TITLE
Yarn.lock (or package-lock.json) should not be git ignored

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#104]
Same pros/cons will work for both.

https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control

https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

I would go for yarn as it's the think we find the most in the entire fb/react ecosystem.

**Comment by wokalski** [comment]
It shouldn't indeed.

**Comment by MoOx** [comment]
Open for yarn.lock?

**Comment by wokalski** [comment]
yup

**Comment by nhducit** [comment]
this issue will be fixed once this PR is merged
https://github.com/reasonml-community/bs-react-native/pull/103

**Comment by arnarthor** [comment]
Fixed in #103
