### ISSUE TITLE
Pct(100.) is transformed to "100.%", should be "100%"

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#109]
The JS code generated by `Pct(100.)` is actually working in react-native projects, but not when used in a browser, via react-native-web (browsers don't like the "100.%").
We should adjust this behavior (as discussed on Discord with @wokalski)

**Comment by wokalski** [comment]
Note to self/anybody willing to work no this one. The solution is simple: Instead of using `string_of_float` in `Style.re` use `Printf.sprintf` with `"%.2f"` format.

**Comment by MoOx** [comment]
Or append “0%” instead of just “%”. That will work too.
