### ISSUE TITLE
Typo in 0.4.0-beta.2 Release Notes

### ISSUE THREAD

**Issue by gbau** [reasonml-community/bs-react-native#116]
In the second bullet of the Update Guide, `node_modules/bs-react-native/update_scripts/styles_v1_to_v2` should be changed to `node_modules/bs-react-native/upgrade_scripts/styles_v1_to_v2`. The former path is invalid.

**Comment by MoOx** [comment]
Thanks for reporting! Fixed.

**Comment by gbau** [comment]
@MoOx also worth noting that I wasn't able to run the `styles_v1_to_v2.exe` executable at first and received this error:
```
/bin/sh: refmt: command not found
Fatal error: exception End_of_file
```
but installing `reason-cli` globally fixed it.

**Comment by wokalski** [comment]
@gbau sorry, I assumed that you had it. Out of curiosity, what's the reason you didn't have global refmt?

**Comment by gbau** [comment]
@wokalski I hadn't needed to install it before. I've been using `bs-platform' to compile reason to JS and never ran into any issues.

**Comment by Tav0** [comment]
so I installed refmt globally only, but still doesn't work.

**Comment by wokalski** [comment]
@Tav0 are you on Windows? What’s the name of the global refmt executable ?

**Comment by Tav0** [comment]
@wokalski I'm OSX. So I installed refmt by doing `npm install -g refmt`, I'm assuming that's the right one, right? I went to `/usr/local/lib/node_modules/refmt/` and couldn't really find an exec in there. So then, I tried downloading reason-cli (that's another problem) and when I tried to installed it by npm, it would just throw me an error `cb() never called`. I can install other modules just fine, so I'm guessing reason-cli is also acting up. I downloaded the darwin binaries of reason-cli and in there I found the exec for `refmt` and refmttype` (not sure if I need this one) I put these two inside the npm global path inside `refmt`, but still same error when trying to exec `styles_v1_to_v2.exe`

**Comment by Tav0** [comment]
https://github.com/reasonml-old/refmt-js

These are pretty much all the files `npm install -g refmt` gives, but then again this repo is deprecated so I'm not sure how you guys assume refmt is installed globally. Is there another repo?

**Comment by wokalski** [comment]
@tav0 @gbau the reason I’m surprised is that global refmt is among the tools needed for editor integration.

Most people install them via a global reason-cli install.

**Comment by Tav0** [comment]
@wokalski What can I do in this case? ._.

**Comment by wokalski** [comment]
@tav0 could you report this issue on the discord channel ?

**Comment by Tav0** [comment]
Will do @wokalski thanks for the replies!

**Comment by wokalski** [comment]
@Tav0 I mean the issue when installing `reason-cli`. There's something wrong happening, i.e. a bug :)
