### ISSUE TITLE
Compiled JS depends on nonexisting reasonReact, which exists as ReasonReact

### ISSUE THREAD

**Issue by jappeace** [reasonml-community/bs-react-native#118]
I got this error:

    Unable to resolve reason-react/lib/js/src/reasonReact.js" from ".//lib/js/re/app.js"

Which I worked around by changing:

    var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

Into 

    var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

I guess I'll fix this with make by running a sed command over all generated files, it'd be better if this was solved correctly though.

**Comment by MoOx** [comment]
Looks like a dup of #102. Should be fixed in [latest beta](https://github.com/reasonml-community/bs-react-native/releases/tag/v0.4.0-beta.2).

**Comment by wokalski** [comment]
yup, closing. @jappeace let us know if something doesn't work after upgrading.
