### ISSUE TITLE
Standarize polymorphic API convention

### ISSUE THREAD

**Issue by wokalski** [reasonml-community/bs-react-native#12]
Currently some of our APIs use suffix based convention (e.g. `diffClampPct` and `diffClamp`) . Others use polymorphic variants. e.g. here:

```
  let interpolate:
    t =>
    inputRange::list float =>
    outputRange::[< | `float (list float) | `string (list string)] =>
    ...
```

It would be great to somehow standardise the naming convention and probably write it down somewhere.

**Comment by saschatimme** [comment]
I think we should explore GADTs outside of style also, with this we could avoid/reduce the use of `Obj.magic` or the `Encode.` which is still somewhere.

**Comment by wokalski** [comment]
This has been solved for styles. There are some remaining uses for instance in animation APIs.

**Comment by MoOx** [comment]
We are going to do our best in next rewrite
