### ISSUE TITLE
Maybe update peerDependencies

### ISSUE THREAD

**Issue by brentvatne** [reasonml-community/bs-react-native#120]
Does bs-react-native still target react-native ^0.46? What about reason-react 0.2.4?

After the update to 0.5.0 I was able to update reason-react to ^0.3.0 with no issues, but I get peerDependencies warnings from npm now about my react-native and reason-react versions.

(I updated reason-react-native-scripts anyways, but warned in README that you will get a peerDependencies warning)

**Comment by wokalski** [comment]
It should be 0.3.0. Consider it a bug. When it comes to the RN version - we can do it too but I don’t have time to go through possible breaking changes there.

**Comment by wokalski** [comment]
It depends on reason-react 0.3.0 now. The remaining issue is the RN upgrade.

**Comment by mobily** [comment]
It has been done here: #160, the current version of RN is `0.53.3`, and `reason-react` is `0.3.4`. However, I'd like to update particular dependencies once again (the latest version of RN is `0.54.x`). I think we can close this issue for now.
