### ISSUE TITLE
Support react-native-web?

### ISSUE THREAD

**Issue by jbaxleyiii** [reasonml-community/bs-react-native#122]
I think this is the library where it issue is, but using this with react-native-web results in a lot of react warnings. I'm assuming its because there may be some defaults being passed to the underlying View implementation that warns on react-native-web?

<img width="1184" alt="capture" src="https://user-images.githubusercontent.com/4967600/34176085-ae18f30a-e4cc-11e7-9360-510d09435633.PNG">

**Comment by MoOx** [comment]
I am having this issue (as I use react-native-web intensively this days).
Reason is by definition strongly typed, so all props are passed (no "random" spread). The direct consequence is that all native only props are spread to RNW.
It's clearly a react-native-web problem. An effort has been made already in some components but should be continued. RNW should just extract all unused props and not spread those into dom components. Example of this technique already done in some places https://github.com/necolas/react-native-web/blob/556dc8926eabe07b3bd20a29f679802ae0a12ab0/src/components/View/index.js#L42-L48
You should open an issue over there so we can continue the effort.
