### ISSUE TITLE
WebView Bool Props aren't converted to JS booleans

### ISSUE THREAD

**Issue by FiberJW** [reasonml-community/bs-react-native#126]
Hello,

I'm using a WebView in this line
`<WebView source=(WebView.source(~uri=url, ())) startInLoadingState=true />` 
and I got an RN yellow box saying there's a failed prop type, it expected a boolean but got a number. I'm assuming ReasonML just placed a `1` instead of `true` in this compilation result.

https://github.com/reasonml-community/bs-react-native/blob/master/src/components/webView.re#L121

Also, when trying to replace the ReasonML, `true` with `Js.true_`,  the compiler says it expects a `bool` and not a `Js.boolean`. After reading some code in bs-react-native, I can foresee this bool-JS.boolean translation being a problem in a lot of the props-mapping that's done here.

The prop ends up working as expected, because `1` is truthy in JS, but if booleans were properly converted that would reduce a lot of friction for those new to writing bs-react-native projects.

Thanks for taking the time to acknowledge this issue!

-- Juwan

**Comment by wokalski** [comment]
Consider this a bug. We normally convert `bool` to `Js.boolean`.

**Comment by ulrikstrid** [comment]
I think this should be closed as it's fixed in bucklescript right?

**Comment by wokalski** [comment]
Correct @strid
