### ISSUE TITLE
Style.combine behaves differently from Style.flatten

### ISSUE THREAD

**Issue by desmond-dsouza** [reasonml-community/bs-react-native#129]
Should these two yield equivalent styles? 
```
Style.(flatten([|style([backgroundColor("blue")]), style([fontSize(Float(32.))])|]))
```
and
```
Style.(combine(style([backgroundColor("blue")]), style([fontSize(Float(32.))])))
```
The second one loses `fontSize`.

**Comment by desmond-dsouza** [comment]
Hmm. I cannot reproduce this now, and suspect I did something incorrectly. Please ignore if you cannot reproduce.

**Comment by wokalski** [comment]
It's weird because I've had the same thing.

**Comment by wokalski** [comment]
I think we should remove one of those.

**Comment by MoOx** [comment]
What do you think about removing flatten?
We could pipe combine.

```reason
Style.(
  style([backgroundColor("blue")])
  ->combine(style([fontSize(Float(32.))])
  ->combine(style([color(String("#333))])
)
```

Recently I even added combineOptional that allow to combine easily an option(Style.t) (see `~style=?`).

**Comment by MoOx** [comment]
I hope this makes the situation better aa4685d12559d7f47f22d2f9c436f06bd1de27fb
