### ISSUE TITLE
SectionList bug in bindings causes Reason types for section to not match actual run-time values

### ISSUE THREAD

**Issue by desmond-dsouza** [reasonml-community/bs-react-native#132]
Here is a gist: https://gist.github.com/desmond-dsouza/5bfb5f6f1d17fcd65bb7f54b8dccabbe#file-gistfile1-txt-L68
Line 68 uses `[%bs.raw` to correctly access 
```
s##section##key
```
on a Js runtime object `s` (representing a `section` as passed to the `renderSectionHeader` callback) that looks like:
```
s = {"section":  {"data": ..., "key": "Section A"} }
```

However, the bindings (not sure where specifically) lead Reason to type-error on:
```
s##section##key
```
and instead insist on:
```
(s##section).key
```
which of course is `undefined` on that run-time value.

**Comment by MoOx** [comment]
New bindings should cause any issue.
