### ISSUE TITLE
Directions on README make assumptions that are not explicit.

### ISSUE THREAD

**Issue by StevenXL** [reasonml-community/bs-react-native#135]
Hi, 

It seems like the README assumes that the person already has a react native project.

Is this the case? If so, that should be made explicit.

(Sorry if I am misunderstanding the directions or missed the relevant section of the README).

**Comment by wokalski** [comment]
No, it doesn't assume that. Feel free to PR that. I thought the instructions were pretty clear.

**Comment by wokalski** [comment]
It does assume that and it's written explicitly in the first paragraph.
