### ISSUE TITLE
Easing

### ISSUE THREAD

**Issue by gilbert** [reasonml-community/bs-react-native#138]
Is `Easing` bindings being worked on by anyone? If not, I'd be willing to contribute if you point me in the right direction.

**Comment by wokalski** [comment]
They are not being worked on. Thank you!

**Comment by gilbert** [comment]
Could you point me in the right direction on what to do? I know about the [JS interop docs](https://reasonml.github.io/docs/en/interop.html), but that's about it.

**Comment by wokalski** [comment]
@gilbert it's hard to say because I don't know what are your concerns in particular. Just try and we'll guide you from there.

**Comment by gilbert** [comment]
I'm just asking for some getting started advice. Let me try to phrase it differently. What general plan do you take when you want to implement a new library's bindings in reasonml?

**Comment by wokalski** [comment]
My workflow is taking the source or documentation, preferably along with flow/ts definitions and typing them one by one. I create a `re` file and start putting `external`s there.

**Comment by ulrikstrid** [comment]
@gilbert there has recently been a few PRs that added new bindings, like clipboard. Have a look at those and if you need additional pointers ask here or on the reason discord.

**Comment by wokalski** [comment]
Yeah, I'm closing this one. Waiting for your PR though!
