### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by wokalski** [reasonml-community/bs-react-native#14]
The APIs are getting more and more different from the JS version. It'd be great to have some format of documentation. What are the best options? `ocamldoc`?

cc @chenglou @jordwalke

**Comment by grsabreu** [comment]
Would be nice to have the docs generated with https://github.com/jaredly/docre

**Comment by wokalski** [comment]
yes, absolutely. `docre` works for the most part so thankfully it's not the issue of tooling anymore.

**Comment by grabbou** [comment]
What is the current status of this? At Rebolt, for time being, we have created a documentation covering most of the APIs by hand. While I agree it would be beneficial to have automatically generated documentation, it would be great to still have a hand-made section containing guides and getting started samples.

Let me know where we are here and how we can help.

**Comment by wokalski** [comment]
It depends how far we want to go with this. It'd be best to generate documentation using `odoc` because it's super good. That said, even though odoc does support Reason, there's no bucklescript runner. If we want to have proper docs for future projects, I'd say, let's try to run odoc with bucklescript. For now though, the docs generated by hand are good enough.

**Comment by wokalski** [comment]
cc @ryyppy

**Comment by ryyppy** [comment]
@wokalski Yeah, I would suggest bear with us a little bit longer until we get the odoc story a little bit more polished / documented ... at some point we would like to try to generate the API docs of reasonml.github.io with odoc as well

cc @rizo

**Comment by wokalski** [comment]
I think we are a good testing ground. Even if you have something sorta-kinda-hacky working, I'd love to take a look at it.

**Comment by grabbou** [comment]
@wokalski okay, let's keep this issue open while we are investigating. I will try to move the documentation from Rebolt onto here in the meantime.

**Comment by wokalski** [comment]
awesome.

**Comment by wokalski** [comment]
@ostera has added BuckleScript support for odoc. That's a great news!

**Comment by grabbou** [comment]
Interesting! That sounds like an ideal plan for remote hackathon one day? :fire:

**Comment by wokalski** [comment]
I'm reopening since the module reference is not accessible from the main docs page.

**Comment by grabbou** [comment]
Oh there's Status page link from the main docs -> https://reasonml-community.github.io/bs-react-native/BsReactNative/status.html

Links itself don't work due to issues with namespacing - no easy fix for now, unless we do it manually (which is probably what I am going to do in this case).

**Comment by wokalski** [comment]
Ok, is there an issue for that already? If not, we can create a new one or use this one.

**Comment by grabbou** [comment]
Not a dedicated one tho. There's #260 PR, but I am wondering whether we
should do manual links vs manual namespace for now.

Don't think it makes sense to change the workflow and have added
development effort for the sake of automatically generated documentation.
I'd rather fix it in there.

**Comment by grabbou** [comment]
I'll do it right now manually and open up a new PR that closes this issue.

**Comment by wokalski** [comment]
Sounds great!
