### ISSUE TITLE
onEndReached mistyped

### ISSUE THREAD

**Issue by maarekj** [reasonml-community/bs-react-native#149]
In the [documentation](https://facebook.github.io/react-native/docs/flatlist.html#onendreached) of react-native, *onEndReached* is of type `(info: {distanceFromEnd: number}) => void` but in `flatList.rei` and `sectionList.rei` the type is `{. "distanceFromEnd": float}`. 

Shouldn't it be `{. "distanceFromEnd": float} => unit` instead ?

**Comment by ulrikstrid** [comment]
I think you're correct, please open a PR 👍

**Comment by mobily** [comment]
Fixed, thanks @maarekj for the contribution 🎉
