### ISSUE TITLE
WebView Js.nullable instead of option

### ISSUE THREAD

**Issue by maarekj** [reasonml-community/bs-react-native#151]
It seems to me that in WebView.rei, we should change `option(t)` to `Js.nullable(t)`
```reason
~onNavigationStateChange: {
  .
  "url": option(string),
  "title": option(string),
  "loading": option(bool),
  "canGoBack": option(bool),
  "canGoForward": option(bool)
} => unit
```
to
```reason
~onNavigationStateChange: {
  .
  "url": Js.nullable(string),
  "title": Js.nullable(string),
  "loading": Js.nullable(bool),
  "canGoBack": Js.nullable(bool),
  "canGoForward": Js.nullable(bool)
} => unit
```

Indeed no conversion is done in `WebView.re`

**Comment by grabbou** [comment]
FYI: WebView is going to be removed from React Native soon anyway (already being extracted).

**Comment by maarekj** [comment]
@grabbou 😲What will WebView be replaced by?

**Comment by grabbou** [comment]
Nothing :) It's going to be in a separate package as we are working on making the core even smaller. You can follow updates here: https://github.com/react-native-community/discussions-and-proposals/pull/3

**Comment by MoOx** [comment]
WebView as ben removed & won't be in the upcoming rewrite.
