### ISSUE TITLE
Make private types under TypesRN and Props public

### ISSUE THREAD

**Issue by jamieparkinson** [reasonml-community/bs-react-native#153]
Apologies for opening an issue for a question, but either I've misunderstood how to do things (likely) or this can be resolved with a PR 🙃 

How come there's no public interface for `Props`? Specifically: I have a function that uses `PanResponder.panHandlers` and thus returns the `Props.touchResponderHandlers` type. It works fine, but it seems like I can't define a signature for the module in which said function lives without access to this type: is there a reason why it's not exposed and/or a way in which I can define the signature without having direct access to the type?

**Comment by wokalski** [comment]
@jamieparkinson Could you show some snippets? It's hard to wrap your head around things given only a description.

Generally speaking, we leave types abstract to make the API as simple as possible.

**Comment by jamieparkinson** [comment]
Sure! A minimal example would be that I'd like to write something like:

```
module type ExampleType = {
    let getHandler: unit => BsReactNative.Props.touchResponderHandlers; 
};

module Example = {
    let responder = PanResponder.create(...);
    let getHandler = () => PanResponder.panHandlers(responder);
};
```

But afaik I can't use `BsReactNative.Props.touchResponderHandlers` due to the `Prop` module's privacy. Is there a way round this (or just something I've missed)? I thought I might be able to use an abstract type in the interface but this seems to just move the issue to the module itself...

**Comment by wokalski** [comment]
`touchResponderHandlers` should be public. But I think that `props` module should remain private. It's an implementation detail. Maybe we can move `touchResponderHandlers` somewhere?  Same applies to `TypesRN` module. I think all common types should live in one module. Either called `Common` or (IMO slightly better) in modules like `Insets` or `TouchResponder`. Then they can be properly grouped. It's a mess in that area, geez.

**Comment by jamieparkinson** [comment]
I think I agree on the common types approach, but what do you think about (at least for the short term) putting `touchResponderHandlers` in the `PanResponder` module? The main issue I can see with this is that then `View` depends on `PanResponder`...

**Comment by wokalski** [comment]
I think temporarily TypesRN should be renamed to Types/Common and `touchResponderHandlers` ought to be put there.

**Comment by jamieparkinson** [comment]
Cool, that sounds good to me! :) Thanks for the help. I'm a bit busy atm but will try to PR in the next couple of days

**Comment by wokalski** [comment]
@jamieparkinson fantastic, looking forward to it.
