### ISSUE TITLE
Style height(Js.Json.null) or width(Js.Json.null)

### ISSUE THREAD

**Issue by GTDev87** [reasonml-community/bs-react-native#165]
`height` and `width` want to take a type `BsReactNative.Style.pt_pct_animated_interpolated`. Because of legacy react native behavior, `null` and `undefined` are useful options.  https://medium.com/the-react-native-log/tips-for-react-native-images-or-saying-goodbye-to-trial-and-error-b2baaf0a1a4d

If not an extension of properties for height and width, an unsafe style prop would be useful.

**Comment by GTDev87** [comment]
https://github.com/reasonml-community/bs-react-native/pull/166

**Comment by benadamstyles** [comment]
Was any solution found for this? Your PR was closed but it doesn't seem like anyone offered any alternative, or have I missed something? We still need to be able to pass `null`, currently I'm doing `[%raw "[\"width\", null]"]` but it would be great to have a typesafe solution!

**Comment by MoOx** [comment]
See 
https://github.com/reasonml-community/bs-react-native/pull/166#issuecomment-377185382

**Comment by benadamstyles** [comment]
@MoOx that PR was closed. Does that mean this is a won’t-fix?

**Comment by MoOx** [comment]
This PR has been closed because we don't think the implementation offered by it wasn't a good fit (it's opening door to unsafe usages that you probably don't want - and if you really do weird things, just is js directly).

The comment I linked mentioned an alternative solution we would be open to that may resolve the initial issue.

**Comment by benadamstyles** [comment]
Ah ok, thanks. I will PR!

**Comment by MoOx** [comment]
This issue needs to be revisited with new bindings. Feel free to report with more details accurate to new bindings or directly offer a fix in a PR.
