### ISSUE TITLE
Unify Animated value types to use phantom types instead of being separate

### ISSUE THREAD

**Issue by wokalski** [reasonml-community/bs-react-native#167]
`Animated` API is a bit of a pain to use because of the distinction between `Interpolation` and `Value`. Instead of two separate types - `Interpolation.t` and `Value.t` we could introduce a single type `value('typ)`. `Interpolation.t` would become `value(interpolation)` and `Value.t` would become `value(simple)`. 

It'd follow that functions like `interpolate` could be used with both of those and likewise passing an animated prop to components would be super easy.

**How it'd look**

```
/* Animated.rei */
type simple;
type interpolation;
type value('typ);

type extrapolate =
  | Extend
  | Clamp
  | Identity;

let interpolate:
    (
      ~value: value('any),
      ~inputRange: list(float),
      ~outputRange: [< | `float(list(float)) | `string(list(string))],
      ~easing: Easing.t=?,
      ~extrapolate: extrapolate=?,
      ~extrapolateLeft: extrapolate=?,
      ~extrapolateRight: extrapolate=?,
      unit
    ) =>
    value(interpolation);

let setValue: (value(simple), float) => unit;
```

**Comment by grabbou** [comment]
Thanks @wokalski for wrapping that into an issue. If you don't plan on working on it anytime soon, happy to step in.

**Comment by jamieparkinson** [comment]
Have been working with the Animated API a lot recently and like the sound of this! @grabbou @wokalski if I can do anything to help 🙂

**Comment by wokalski** [comment]
I’m deep in other things. Definitely not planning to work on it anytime soon.

**Comment by wokalski** [comment]
Also, what's important is that it's possible to retain backwards compatibility here. Although it'd be probably desired to add some deprecation warning for the existing apis.
