### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kolljohnson** [reasonml-community/bs-react-native#168]
I noticed that there doesn't seem to be any automated tests within the project as of yet. Is this something that'd be reasonable to start adding to the project, or are there issues that I'm not aware of? I was thinking of adding some integration and snapshot tests that could be a good way to get started on some test coverage.

**Comment by wokalski** [comment]
Yes, it is reasonable but there are no satisfying tools for testing bindings as of now. 

https://reasonml.chat/t/what-is-your-approach-to-test-a-reasonreact-binding/196/10?u=wokalski

Here's a comment regarding testing bindings.

**Comment by kolljohnson** [comment]
Shoot, I figured something like that was the case. Thanks for clarifying!
