### ISSUE TITLE
style textTransform not supported

### ISSUE THREAD

**Issue by rsaccon** [reasonml-community/bs-react-native#169]
in `style.re` I could not find anything which relates to: https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform.

**Comment by wokalski** [comment]
Feel free to close when resolved @MoOx @rsaccon

**Comment by MoOx** [comment]
I guess keeping this open doesn't make sense. It's not the responsibility of this repo to handle this.

**Comment by MoOx** [comment]
My 2 cents about this https://github.com/necolas/react-native-web/issues/905
