### ISSUE TITLE
Anybody using bs-react-native bindings with react-native-web ?

### ISSUE THREAD

**Issue by rsaccon** [reasonml-community/bs-react-native#170]
There are some minor platform specific differences, for example react-native-web allows to use `em` or `rem` for spacing. In untyped JS, this is easy to deal with, no code changes required. 

What would be the ReasonML way to deal with such cases ? Put platform specific code right into bs-react-native ? I guess not. 

A  kind of monkey-patching wrapper module ?

**Comment by rsaccon** [comment]
ok, found some discussion  related to this here:  https://github.com/reasonml-community/bs-react-native/pull/123

**Comment by MoOx** [comment]
I use it, and I avoid at all cost web stuff only. No just because of the bindings limitation. If I need to, I use web stuff directly without the bindings.

I guess the only way would be to have a bs-react-native-web. Maybe scripted from this one?

**Comment by rsaccon** [comment]
@MoOx thanks, but how do you "use web stuff directly without the bindings" ?

E.g. I would like to use Hover functionality on the web platform. In react-native-web there is [glitch](https://glitch.com/edit/#!/imaginary-lycra) where the following implementation is suggested (just render function here):

```
 render() {
    const { children, onHoverIn, onHoverOut } = this.props;
    const child = typeof children === 'function' ? children(this.state.isHovered) : children;

    return React.cloneElement(React.Children.only(child), {
      onMouseEnter: this._handleMouseEnter,
      onMouseLeave: this._handleMouseLeave
    });
 } 
```

I tried to implement that in reason-react like this:
```
open BsReactNative;

type action =
  | Toggle;

type state = {isHovered: bool};

let component = ReasonReact.reducerComponent("Hoverable");

let make = (~isHoverEnabled, children) => {
  ...component,
  initialState: () => {isHovered: false},
  reducer: (action, state) =>
    switch (action) {
    | Toggle => ReasonReact.Update({isHovered: ! state.isHovered})
    },
  render: self =>
    <div
      onMouseEnter=(
        (_) =>
          if (isHoverEnabled^ && ! self.state.isHovered) {
            self.send(Toggle);
          }
      )
      onMouseLeave=(
        (_) =>
          if (self.state.isHovered) {
            self.send(Toggle);
          }
      )>
      (children(~isHovered=self.state.isHovered))
    </div>,
};
```
it actually works, but I guess this is not as it is supposed to be done. 

So what is the best way to get something like this done in reason react (or if possible, directly in "web" as you mentioned) ?

**Comment by MoOx** [comment]
Solutions I see are:
- recreate locally some components interfaces and add missing parts for RNW
- make a JS component exposed to RE
- make a web component (JS or RE) without using (bs-)RN APIs (but web primitives instead).

**Comment by wokalski** [comment]
Feel free to close this one unless you're gonna have some actionable outcome 👍

**Comment by rsaccon** [comment]
I will explore a bit more the different options to get RN nicely working on web. For now, closing the issue.
