### ISSUE TITLE
There are no docs which leads to lower than desired adoption and contribution rate

### ISSUE THREAD

**Issue by vnovick** [reasonml-community/bs-react-native#184]
Currently there are no docs for bs-react-native.
We can just put comments for every api and docs will be auto generated.

@chenglou, Is there specific format of comments you prefer? Where it will be auto generated?

**Comment by grsabreu** [comment]
Possible duplicate https://github.com/reasonml-community/bs-react-native/issues/14

**Comment by wokalski** [comment]
yes, closing.
