### ISSUE TITLE
Not sound WebView `onNavigationStateChange` bindings

### ISSUE THREAD

**Issue by grsabreu** [reasonml-community/bs-react-native#186]
The bindings declare that `onNavigationStateChange` receives options https://github.com/reasonml-community/bs-react-native/blob/master/src/components/webView.rei#L121 from JS and there is no conversion in the code, so they should be `Js.Null_undefined.t`. But I also think they are never null/undefined.
I'm going to send a PR fixing this.

**Comment by grsabreu** [comment]
Takes on https://github.com/reasonml-community/bs-react-native/pull/152

**Comment by wokalski** [comment]
Fixed in #200
