### ISSUE TITLE
Hot module reloading

### ISSUE THREAD

**Issue by wokalski** [reasonml-community/bs-react-native#19]
It looks like hot module reloading doesn't work currently.

**Comment by saschatimme** [comment]
I investigated a little bit, and it seems that we would need to patch https://github.com/gaearon/babel-plugin-react-transform to get it working

**Comment by grsabreu** [comment]
It's working fine for me in RN > 48

**Comment by wokalski** [comment]
@gunnigylfa @arnarthor did you play with this in your applications?

**Comment by arnarthor** [comment]
Yup, we've had hot reloading from the beginning. We are using Expo though, so I don't know if the setup differs from `react-native init`. @cullophid for example could never get hot reloading working in his app. @cullophid are you using Expo or `react-native init`?

**Comment by ucokfm** [comment]
Here my workaround to enable hot reloading, by modify index.js :
```
import React from 'react';
import { AppRegistry } from 'react-native';

import { app as ReasonApp } from './lib/js/re/app.js';

class App extends React.Component {
  render() {
    return <ReasonApp />;
  }
}

AppRegistry.registerComponent('MyAwesomeProject', () => App);
```

**Comment by enieber** [comment]
I have problem follow the staps of post [Getting started with reasonml and react-native](https://blog.callstack.io/getting-started-with-reasonml-and-react-native-299476389c3e) in **react-native 0.57.8** and **bs-react-native 0.10.0** but I no follow the staps of @ucokfm

**Comment by muhammadridho** [comment]
i'm followed the @ucokfm steps, it works. i think return from the instance / class is different from reactreason component. 

so this is just my guess.

**Comment by MoOx** [comment]
I don't really rely on hot loading. I am going to close & things might been affected by reasonreact 0.7 release & upcoming rewrite.
Feel free to reopen or ask for it if this is still causing & an issue when those bindings are released (or if you try with current master branch)
