### ISSUE TITLE
Expand disclaimer

### ISSUE THREAD

**Issue by vemv** [reasonml-community/bs-react-native#194]
Hi!

As an outsider assessing this project, the following disclaimer doesn't seem clear enough:

> There are some components and APIs missing.

What does that mean in practice? Can I still use the missing components through javascript interop? Or as a Reason developer targeting RN, there would be apis/component I simply cannot use as of today?

Thanks - Victor

**Comment by wokalski** [comment]
Good question. In general it means that not the whole API surface of React Native is supported. That said most of it is indeed covered (with occasional bugs 😄 ). 

Things which are not in bs-react-native yet are usually very easy to bind to in the user space (in your project through normal JS ffi). Feel free to contribute if you encounter such cases.

Do you have a suggestion how to rephrase it?

**Comment by vemv** [comment]
Thanks for the clarification! Here's a suggested completion:

> There are some components and APIs missing. But fear not; you still can use uncovered APIs through JS ffi.
