### ISSUE TITLE
Incorrect bindings for gesture handlers

### ISSUE THREAD

**Issue by eldh** [reasonml-community/bs-react-native#203]
It seems like the bindings for gesture responder handlers are incorrect. They assume the input is `NativeEvent` when it is in fact an object like `{nativeEvent: NativeEvent}`. I'll try to whip up a PR soon but I thought I'd create an issue just to track it.

**Comment by sgny** [comment]
I understand that you are referring to [panResponder](https://github.com/reasonml-community/bs-react-native/blob/master/src/panResponder.re), is that right?

As you observe, the object should have a `nativeEvent` key of type `NativeEvent`. There is the type `callback('a)` defined as a JS object: `{. "nativeEvent": RNEvent.NativeEvent.t}`. If you consider the type signature for the function `callback`, however, it takes as argument a function `x` with signature `(NativeEvent.t, gestureState) => 'a` and returns another function which takes arguments `(event, state)`. `callback` applies function `x` to arguments `event##nativeEvent` and `jsGestureState` which itself is `state` appropriately converted into the type of the same name. Thus, callback maps a function `x` with signature `(NativeEvent.t, gestureState) => 'a` to a function with signature `(event, state) => 'a` where event is a JS object as defined above and state is of type `jsGestureState`.

As far as I can tell, the signature is fine but perhaps I have reasoned incorrectly or might have misunderstood your concern.

**Comment by eldh** [comment]
No, I was referring not to `panResponder` but to the lower level gesture handlers, that are sent as props to `View` (https://github.com/reasonml-community/bs-react-native/blob/752544cbdeda19914dc2ec769a77b0cf9f2a0ff5/src/components/view.rei#L10). `panResponder` bindings are correct.

**Comment by MoOx** [comment]
Does anyone know if this issue is still relevant with new bindings? @sgny @cknitt

**Comment by sgny** [comment]
Nice coincidence, I was working on `PanResponder` when I saw the mention. That should be available soon, but I want to test a bit before making a PR.

I'll take a look at `touchResponderHandlers` as well and see if everything's in order.

**Comment by sgny** [comment]
Last time, I couldn't devote much time to this, but `Event.NativeEvent.t` is the type in the bindings for the `nativeEvent` key in the `event` object and not the object itself. Accordingly, `touchResponderHandlers` are not correctly specified in the new bindings either.

For `panResponder` in the legacy bindings, functions of type `(RNEvent.NativeEvent.t, gestureState) => 'a` were wrapped by the function `callback` which calls the function on `nativeEvent` extracted from `event` via the `##` accessor, resulting in a function from `({. "nativeEvent": RNEvent.NativeEvent.t}, gestureState) => 'a`. Something similar has to be done for `touchResponderHandlers`.

To keep the bindings light, I propose to specify both to require functions of type `({. "nativeEvent": RNEvent.NativeEvent.t}, gestureState) => 'a`, but also expose a wrapper function similar to `callback`.

**Comment by sgny** [comment]
Function types will be `(~nativeEvent: Event.NativeEvent.t), gestureState) => 'a` to easily extract `nativeEvent`. I should have PR ready soon.

**Comment by sgny** [comment]
To keep the bindings light, I decided Gesture Responder and PanResponder props should, respectively, be of types `Event.t => 'a` and `(Event.t, gestureState) => 'a`.

A wrapper function for each can be defined as before, but should such functions be included or left out to keep the bindings clean?

They could perhaps be illustrated in the documentation but I do feel they are unnecessary redirection.
