### ISSUE TITLE
Merging Rebolt v1 back to bs-react-native

### ISSUE THREAD

**Issue by knowbody** [reasonml-community/bs-react-native#204]
Hey,

As you know, some time ago, we forked `bs-react-native` to learn more about the implementation and experiment with it. Since then I and a couple of contributors from Callstack and outside Callstack have contributed to Rebolt v1.

The work that has been done:
- docs, with examples
- a few missing bindings added
- a few changes to the current bindings that already existed

The changes that we've done have helped us and worked for us internally, and also helped other people who tried adopting ReasonML in their react-native codebases.

As we were saying from the very beginning, the reason for the fork was purely for us to speed up its development and experiment with different approaches and learn from it, so we can work on what we call Rebolt v2. The phase 1 (bindings) is more or less done for us, and we would like to give back what we've learnt to the community and the project that earlier allowed us to start our experimentation on the great foundation.

In the next few days, I'll be working on submitting a PR, first I'll make it a WIP, where I'd like to get some feedback from you on what things should be kept and what things can be merged from Rebolt.

I thought I create this issue as an info before I start submitting the PR.

Hope you are all excited, and we'd like to say big thanks to ReasonML community and `bs-react-native`! 🎉

In the meantime, the rest of the work that we'll be doing in the Rebolt repo will be the work on what we before called Rebolt v2, we will experiment the native compilation and how react-native rewrite in ReasonML can with cross-platform development.

**Comment by wokalski** [comment]
That's a nice surprise. Great! I think we're all happy for this.

**Comment by grabbou** [comment]
Already started doing it via #211 PR

**Comment by ulrikstrid** [comment]
I went through and merged a lot of the PR's from Rebolt
