### ISSUE TITLE
Platform.os binding prevents inlining/optimization

### ISSUE THREAD

**Issue by grabbou** [reasonml-community/bs-react-native#239]
Metro bundler inlines `(ReactNative.)Platform.OS` and `(ReactNative.)Platform.select`, so that when packaging for one platform, the code for the other platform is optimized away.

So if I had

```reason
[@bs.module "react-native"] [@bs.scope "Platform"] external os : string = "OS";

if (os === "ios") {
  Js.log("ios");
} else {
  Js.log("android");
};
```

this would get compiled by BuckleScript to

```js
if (ReactNative.Platform.OS === "ios") {
  console.log("ios");
} else {
  console.log("android");
}
```

and Metro Bundler would inline ReactNative.Platform.OS and subsequently optimize the Android branch away for an iOS build.

However, with the current Rebolt bindings, I have

```reason
switch (Platform.os()) {
| IOS(_) => Js.log("ios")
| Android => Js.log("android")
};
```

which gets compiled by BuckleScript to

```js
var match = Platform$Rebolt.os(/* () */0);
if (match) {
  console.log("ios");
  return /* () */0;
} else {
  console.log("android");
  return /* () */0;
}
```

This prevents the inlining/optimization from working.

**Comment by grabbou** [comment]
Cross-posted from https://github.com/callstackincubator/rebolt/issues/66 via @cknitt

**Comment by cknitt** [comment]
I created this issue originally in the rebolt repo.

The new bindings currently being worked on (bs-react-native-next / #344) won't have that problem. (At the moment, they only directly bind `Platform.os` as a string.)
