### ISSUE TITLE
Use new @bs.deriving abstract 

### ISSUE THREAD

**Issue by czystyl** [reasonml-community/bs-react-native#240]
Some of the components and API's uses the old object API that is deprecated by [BuckedScript doc](https://bucklescript.github.io/docs/en/object-deprecated). 
Instead of using deprecated object use the new [`[@bs.deriving abstract]`](https://bucklescript.github.io/docs/en/object) and [`[@bs.deriving jsConverter]`](https://bucklescript.github.io/docs/en/generate-converters-accessors)

List of component contain depricated API:
* [ ] flatList
* [ ] animatedRe
* [ ] cameraRoll
* [ ] scrollView
* [ ] sectionList
* [ ] textInput
* [ ] touchableHighlight
* [ ] touchableOpacity
* [ ] viewPagerAndroid
* [ ] imagePickerIOS
* [ ] linking
* [ ] panResponder
* [ ] utilsRN
* [ ] RNEvent
* [ ] events
* [ ] permissionsAndroid

Feel free to update that list.

**Comment by czystyl** [comment]
The issue is moved from Rebolt repository: https://github.com/callstackincubator/rebolt/issues/47

**Comment by wokalski** [comment]
Do you think it's worth it? I'm not convinced. `Js.t` API is not deprecated anymore. It's been undeprecated. What's the reasoning here? Maybe we should go about it case by case?

**Comment by czystyl** [comment]
We created that list when `Js.t` was deprecated, but I haven't realized that it's undeprecated now. As you mentioned that not all component from the list need changes but in some cases moving to `@bs.deriving` could improve usage of API. I'd keep this list of a possibility of improving and create separate issue/PR for a single component/API.

**Comment by MoOx** [comment]
Does this issue make sense to be opened? Could we open an issue per compo if still relevant?

**Comment by MoOx** [comment]
No need for this anymore, we are going to follow another approach with new rewrite
