### ISSUE TITLE
Add contributor list

### ISSUE THREAD

**Issue by Krizzu** [reasonml-community/bs-react-native#247]
Hey 👋 

Project looks great 🔥 Many great contributions made!
I love the idea of having a list of contributions in visible place (like README), so what about adding it here? Tools like [All-contributions](https://github.com/kentcdodds/all-contributors) could be used to ease the maintain.

WDYT?

**Comment by czystyl** [comment]
It's looking great! Good idea 👍

**Comment by grabbou** [comment]
I think it's a great idea, please do it whenever you have time! (don't forget to add yourself too) :fire:

**Comment by grabbou** [comment]
Note: Once we merge a PR that brings documentation, we should rewrite the whole Readme of this project to focus more on "development" aspects and put "contributors" section at the top. We should also adopt Code of Conduct explicitly.

Everything else, including Getting Started, Status etc. should go to the main documentation.

**Comment by grabbou** [comment]
Update: Started working on implementing this as a part of my documentation/meta update for the project here: https://github.com/reasonml-community/bs-react-native/pull/249

**Comment by grabbou** [comment]
Landed in master: https://github.com/reasonml-community/bs-react-native#contributors. The original issue can be closed now, unless there's someone willing to take on the Git history rewrite task.

**Comment by grabbou** [comment]
Now that I think about it, we can also add another laptop emoji next to those who contributed to Rebolt and link to their commits from there.

https://github.com/reasonml-community/bs-react-native/blob/master/CONTRIBUTORS.md
