### ISSUE TITLE
borderRadius for rounded images

### ISSUE THREAD

**Issue by PierreCapo** [reasonml-community/bs-react-native#250]
Hello all,
I'm trying to make perfectly rounded images, which is usually accomplished by setting width, height, and borderRadius to the same value. Right now, my code is: 
```
<Image
    source=(URI(Image.imageURISource(~uri="https://facebook.github.io/react/logo-og.png", ())))
    style=Style.(style([height(Pt(100.)), width(Pt(100.)), borderRadius(100.)]))
/>
```
The result is a weird disturbed square (see below), and I suspect it's because borderRadius only accepts floats instead of `pt_pct_animated_interpolated` type. What are your thoughts about it ?

![image](https://user-images.githubusercontent.com/26744253/45928567-f80c3b80-bf45-11e8-9083-6eb57efabfe3.png)

**Comment by knowbody** [comment]
if you want to have the rounded image, you would set the `borderRadius` to half of the width or height, so you should set it to `50.`

**Comment by PierreCapo** [comment]
Good catch, seems logical after thinking about it. However the behavior is not the same with vanilla react-native (I had a rounded image). Although that may be not top priority, it would be good to fix it ?

**Comment by knowbody** [comment]
I believe the behaviour is the same in react-native, at least I get the same thing testing on https://snack.expo.io

If this is resolved then please close the issue

**Comment by PierreCapo** [comment]
Exact, my bad, it's actually rendering well on Android but disturbed on iOS.
