### ISSUE TITLE
Move `AnimatedRe.re` to `Animated.re`

### ISSUE THREAD

**Issue by grabbou** [reasonml-community/bs-react-native#253]
Easy task. There's no need to have these two. We should move the content of `AnimatedRe.re` to `Animated.re`.

**Comment by czystyl** [comment]
We can't merge this two files because of the dependency cycle error occurs.

**Comment by grabbou** [comment]
CC: @wokalski - maybe we should just rename the `AnimatedRe` to `Animated` in the docs :D

**Comment by wokalski** [comment]
I'm sure we can do something about it. I'm adding this to my todo list. I'll take a look at it before Wednesday.

**Comment by grabbou** [comment]
It's probably a matter of creating one or two utilities that are causing a reference cycle! Looking forward @wokalski

**Comment by MoOx** [comment]
Not relevant with new bindings.
