### ISSUE TITLE
Come up with better solution for docs navigation

### ISSUE THREAD

**Issue by vnovick** [reasonml-community/bs-react-native#265]
While I know there is an ongoing effort to improve the docs, I wanted to point out problems that I think will make oboarding pretty hard for new bs-react-native users.

# Docs Navigation
Currently navigation through [docs](https://reasonml-community.github.io/bs-react-native/BsReactNative/index.html) is done via clicking on "status" and then going up and down the tree.
This is not really friendly navigation and I think we need to improve overall navigation through the docs. 
I like more how it looked like for [rebolt](https://rebolt.callstack.com/docs/intro.html)

# Docs Formating
So far most of components docs looks auto generated but even though they are auto generated, `make` functions are unreadable

compare for example these docs:
[ActivityIndicator](https://reasonml-community.github.io/bs-react-native/BsReactNative/ActivityIndicator-BsReactNative/)
[ActivityIndicator(rebolt)](https://rebolt.callstack.com/docs/activity-indicator.html)

This will be dealt in issue #267 when we will migrate docs to rebolt

**Comment by grabbou** [comment]
Regarding `make` being not readable - this is something @ostera is working on right now. I hope it will get fixed really soon.

For now, I think we need to manually write `guide` for `ActivityIndicator` and highlight all its props line by line. Going to work on that tomorrow and submit a PR to suggest one of the potential ways going forward.

In general, I am quite excited to use `odoc` and help make it more user-friendly. Whole community should eventually benefit from improvements we do over time.

**Comment by wokalski** [comment]
odoc is bomb and there's a lot of progress in it recently.

**Comment by grabbou** [comment]
I have just filled in a PR with proposed structure: https://github.com/reasonml-community/bs-react-native/pull/266

I can finish `ActivityIndicator` once there's general conclusion. Happy to see contributions :)

**Comment by grabbou** [comment]
I am working on another PR to fix breadcrumbs. That is, every time you click "BsReactNative" at the top, it should go to "status" page, instead of "home page". Easier to navigate.

**Comment by vnovick** [comment]
@grabbou, I've renamed this issue to docs navigation cause formatting will be gradually fixed by migrating docs from rebolt. #267

**Comment by MoOx** [comment]
I would like to go a step forward with the docs, by using bs-react-native itself to generate the doc UI.
My idea is to use a static site generator that can use react, and use react-native-web+bs-react-native (I am already doing that on a few website and I am quite happy with this, eg: https://github.com/MoOx/moox.io).
I think if we can have [odoc generating json](https://github.com/ocaml/odoc/issues/196) for us with a nice way to retrieve data we would be totally flexible on the website UI.

**Comment by ostera** [comment]
For the record, the next Odoc release will automatically build a navigation from the titles included in the docs of a .mli/.rei file:

Example ref: https://github.com/BuckleScript/bucklescript/pull/3379

![screenshot 2019-02-18 at 15 52 14](https://user-images.githubusercontent.com/854222/53082691-addfb400-34fd-11e9-9815-476bd31e6dff.png)

So you could have docs looking like this: https://ostera.github.io/reactor-web/docs/ReActor/, with none of the manual overhead of keeping that ToC synced.

**Comment by MoOx** [comment]
That's nice!

On the long run, I guess if we ends up having docs as json we could also generate a ToC easily :)

**Comment by MoOx** [comment]
I am working on a new website that will rely on odoc --fragments, see #341
