### ISSUE TITLE
Docs migration from rebolt to bs-react-native 

### ISSUE THREAD

**Issue by vnovick** [reasonml-community/bs-react-native#267]
There was an extensive work done on [rebolt](https://rebolt.callstack.com/docs/intro.html) project for documenting lots of react-native components and APIs.  It will be great to migrate those to bs-react-native by using odoc auto generation with macros

Check the following example how docs should look like:
[Activity Indicator](https://reasonml-community.github.io/bs-react-native/BsReactNative/ActivityIndicator-BsReactNative/)
And this was the corresponding [PR](https://github.com/reasonml-community/bs-react-native/pull/266) by @grabbou 

Currently most of the docs are not migrated and formatted.

I will start opening PRs on docs migration and comment on this issue with PR links.
If you have additional suggestions how to improve docs beyond simple migration from Rebolt, please comment here too.

**Comment by czystyl** [comment]
I'm going to move `Button`

**Comment by MoOx** [comment]
@vnovick has everything being migrated? Can this issue be closed?

**Comment by MoOx** [comment]
Looks like #294 closed this
