### ISSUE TITLE
Missing docs for various APIs

### ISSUE THREAD

**Issue by vnovick** [reasonml-community/bs-react-native#295]
All of the following docs are missing both in bs-react-native and rebolt so need to be written from scratch

- CameraRoll
- BackHandler
- BackAndroid
- AsyncStorage
- AppState
- DatePickerAndroid
- Easing
- GeoLocation
- ImageStyleProps
- Keyboard
- LayoutProps
- NetInfo
- PanResponder
- PixelRatio
- ShadowProps
- StyleSheet
- TextStyleProps
- TimePickerAndroid
- Transforms
- Vibration
- ViewStyleProps

**Comment by vnovick** [comment]
I'm on it. Just opening this issue as separate one so #267 can be closed after #294 is merged

**Comment by MoOx** [comment]
Going to be visible on the up coming website, the sidebar will be a good reminder.
