### ISSUE TITLE
CI is either failing or stuck on docs task

### ISSUE THREAD

**Issue by vnovick** [reasonml-community/bs-react-native#301]
For bunch of branches CI either stuck on docs task:

`ci/circleci: docs Expected — Waiting for status to be reported`

Or failing with `fatal: Unable to find remote helper for 'git+https'`

Latest PRs where it is happening are #300 and #294

**Comment by MoOx** [comment]
I just got this for an tiny PR

https://circleci.com/gh/reasonml-community/bs-react-native/494

```
[odoc] http://github.com/ocaml-doc/odoc.git updated
[odoc] Installing new package description from
http://github.com/ocaml-doc/odoc.git

odoc needs to be installed.
Your request can't be satisfied:
  - odoc.dev is not available because the package is pinned to http://github.com/ocaml-doc/odoc.git, version dev.

No solution found, exiting
[NOTE] Pinning command successful, but your installed packages may be out of
       sync.
Exited with code 3
```

I never used opaml nor odoc, still new to reason, but I may help if I got the right pointer :)

**Comment by MoOx** [comment]
The initial issue & the related PRs have been merged. Opening something new for the recent failures we have.
