### ISSUE TITLE
Transparent git pre-commit hook to run refmt

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#312]
I can make a (short) PR to automatically run refmt on each modified files using husky+lint-staged.
This will avoid PRs having (long) width & will make reviews more easy (as more consistent).

Would the team be ok with that?

Pro:
- pre-commit setup transparent for the contributor (nothing to setup, `husky` handle the thing)
- pre-commit call easy to tweak (in the package.json)

Con:
- Don't work if anyone modify a file from github ui (but anyway it's the same without this setup)

It's pretty easy & fast, see

https://github.com/MoOx/moox.io/blob/09218e36fc94cb6e072ab6543f15c2df5caefb89/package.json#L22-L24

https://github.com/MoOx/moox.io/blob/09218e36fc94cb6e072ab6543f15c2df5caefb89/package.json#L68-L82

**Comment by ulrikstrid** [comment]
Can you also add it so that we check in CI if it has been formatted?

**Comment by MoOx** [comment]
I can probably do that.

**Comment by MoOx** [comment]
I think if I run refmt + build & check git status I should by able to tell if anything is missing from the PR :)
