### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#325]
Because it's cool to have a logo, especially as favicon & stuff (think: website).

This is my "new tab" view of my browser atm

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/157534/53128817-077bc900-3566-11e9-8e66-47bcc3739209.png">

I would like to improve this situation.

I just took some minutes to quickly sketch some things

![bsreactnative-like-community-alt](https://user-images.githubusercontent.com/157534/53128852-237f6a80-3566-11e9-93f8-aabb555407a3.png)
![bsreactnative-like-community](https://user-images.githubusercontent.com/157534/53128853-237f6a80-3566-11e9-885f-f8242ce81776.png)
![bsreactnative-re-react-transparent](https://user-images.githubusercontent.com/157534/53128854-237f6a80-3566-11e9-9df8-78825d34806b.png)
![bsreactnative-redrn](https://user-images.githubusercontent.com/157534/53128855-237f6a80-3566-11e9-8f3d-05743d21e3f0.png)
![bsreactnative](https://user-images.githubusercontent.com/157534/53128856-24180100-3566-11e9-8c59-acf855c8aba2.png)

If someone wants to play, here is the sketch file

[BsReactNative.sketch.zip](https://github.com/reasonml-community/bs-react-native/files/2886723/BsReactNative.sketch.zip)

**Comment by richardbmx** [comment]
Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by MoOx** [comment]
@richardbmx feel free to post some stuff :) Actually this project is a bridge between [react-native](http://facebook.github.io/react-native/) library & the [reasonml](https://reasonml.github.io) language. So we don't have to be original. Just a visual identity that express the mix of those 2 things :)

**Comment by MoOx** [comment]
Here are some others shots

![bsreactnative-rn-black](https://user-images.githubusercontent.com/157534/53151541-c6120a80-35b3-11e9-976b-1bd27eb82a3b.png)
![bsreactnative-weird](https://user-images.githubusercontent.com/157534/53151537-c5797400-35b3-11e9-87ef-9c70e0b273a3.png)
![bsreactnative-rrblue](https://user-images.githubusercontent.com/157534/53151539-c6120a80-35b3-11e9-9095-64f7d9bfb5d1.png)
![bsreactnative-rn-blue](https://user-images.githubusercontent.com/157534/53151540-c6120a80-35b3-11e9-83aa-76554c82d270.png)
![bsreactnative](https://user-images.githubusercontent.com/157534/53151925-91eb1980-35b4-11e9-8d76-c75ba53650cc.png)
![bsreactnative-rn-r-blue](https://user-images.githubusercontent.com/157534/53151926-91eb1980-35b4-11e9-9392-b20cb6485539.png)


Updated [BsReactNative.sketch 2.zip](https://github.com/reasonml-community/bs-react-native/files/2888181/BsReactNative.sketch.2.zip)

**Comment by cem2ran** [comment]
Maybe just keep it simple with React Native logo but with "ReasonML" red background instead of black?

**Comment by MoOx** [comment]
Problem I see is that React Native logo is the same as the react one. Only colors differ. See https://reactjs.org vs http://facebook.github.io/react-native/
That's why I wanted to introduce RN or black color.

**Comment by MoOx** [comment]
Btw, the blue is used came from ReasonReact design https://reasonml.github.io/reason-react/

**Comment by MoOx** [comment]
Which is a variation from the blue used for react(js) logo.

**Comment by cem2ran** [comment]
I like the simplicity of the atom in white (like ReactNative) with a red background like ReasonML. 
Just my 2 cents :)

![bsreactnative](https://user-images.githubusercontent.com/959142/53243248-904e4e00-36a7-11e9-95d5-1bcc6216b0c8.png)

**Comment by MoOx** [comment]
@cem2ran How can we know it's not "reason react" with this logo (especially if you are new to reason/reasonreact/bs-react-native)? That's why I didn't made this one.

More shots with the "RN" idea (could work in black too)

![bsreactnative-rrblue-rn-alt](https://user-images.githubusercontent.com/157534/53395907-62b51d80-39a3-11e9-9c1b-23e3e75082c5.png)
![bsreactnative-rrblue-rn-alt2](https://user-images.githubusercontent.com/157534/53395908-62b51d80-39a3-11e9-87ec-513df55e5b89.png)
![bsreactnative-rrblue-rn](https://user-images.githubusercontent.com/157534/53395909-634db400-39a3-11e9-98e7-8dd6625944a1.png)

And simpler version with RN black + obvious "RE" text

![bsreactnative-rn-black-re-alt](https://user-images.githubusercontent.com/157534/53396296-64331580-39a4-11e9-8ac4-91dfccbef8d6.png)
![bsreactnative-rn-black-re-alt2](https://user-images.githubusercontent.com/157534/53396298-64331580-39a4-11e9-9a34-5520663166fb.png)
![bsreactnative-rn-black-re](https://user-images.githubusercontent.com/157534/53396299-64331580-39a4-11e9-8bfd-aaeb5a46960c.png)

**Comment by cem2ran** [comment]
In that case I vote for the last one. Original RN logo with RE text within. Might be my eyes or the color, but spacing between RE on blue version looks a little off. I might even try it with red, but black looks 👌

Should probably get a designer on the task 😅

**Comment by Freddy03h** [comment]
Following logic:

|  | JS | Reason |
| :------------ | :-------------: | -------------: |
| React | ![react](https://reactjs.org/favicon.ico) | <img width="52" alt="Capture d’écran 2019-03-12 à 16 53 11" src="https://user-images.githubusercontent.com/1412159/54214921-5d012100-44e7-11e9-98fb-0d70bd6a2985.png"> |
| React-Native | ![react-native](https://facebook.github.io/react-native/img/favicon.png) |  |

 There is no logic 😅

ReasonReact logo shouldn't use the white logo because it's react-native. It should be black on blue background, and react-native-reason black logo on white background. But theses ideas aren't great too…

<hr/>

<img width="151" alt="Capture d’écran 2019-03-12 à 16 56 35" src="https://user-images.githubusercontent.com/1412159/54215918-0399f180-44e9-11e9-8f59-122760f76df3.png">

_I'm not a good idea_

<hr/>

So, because there is no logic for now, and there is no significants distinctions between React / ReactReact and React-Native (only colors), I think we can use a new symbol like **RE** logo inside the react-native logo to avoid confusion.


![](https://user-images.githubusercontent.com/157534/53396299-64331580-39a4-11e9-8bfd-aaeb5a46960c.png)
