### ISSUE TITLE
Deprecation of deprecated RN core modules (AsyncStorage, NetInfo etc)

### ISSUE THREAD

**Issue by DCKT** [reasonml-community/bs-react-native#331]
Hello, 

Following the latest version of React Native (0.59), AsyncStorage will be deprecated and removed in the future.
`AsyncStorage` has been moved to https://github.com/react-native-community/react-native-async-storage. We should move the bindings to another repo too I think.
If needed, I can take some times to do this.

**Comment by MoOx** [comment]
I guess we can do bs-react-native-async-storage. Does anyone around know who to ask to get a new repo to rn-community org?
Otherwise we could imagine turning this repo into a monorepo/mutli package?
Thoughts?

**Comment by DCKT** [comment]
I think monorepo could be great. Better and simpler management than 10+ future small repo

**Comment by MoOx** [comment]
Closing in favor of #474
