### ISSUE TITLE
Remove variants for props that expect string values?!

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#342]
I want to make this bindings accessible I was wondering if we could remove polymorphic variants that are used accross bindings to send string to rn.
Sure that's less safe, but this conversion require maintenance, can be imcomplete & so on...

Typically we have tons of  things like that

```
"indicatorStyle":
              indicatorStyle->Belt.Option.map(
                fun
                | `default => "default"
                | `black => "black"
                | `white => "white",
              ),
```

So sure, that's safer. But it require more code/maintance for something that evolve (RN development is on fire)...

On the other hands, we could go aggressive and use normal variant type with handcoded *ToJs encoder for js... Even safer but more maintenance.

Thoughts?

**Comment by MoOx** [comment]
As a wise man said, 

> you might catch like one bug ever from a typo, then waste everyone's time telling about the poly variant api

**Comment by MoOx** [comment]
Using `[@bs.string]` with lowercase polymorphic variants make the maintenance easier tho & keep type safety...

@cknitt thoughts?

**Comment by cknitt** [comment]
Absolutely agree - `[@bs.string]` with lowercase polymorphic variants is what I am using right now in https://github.com/cca-io/cca-bs-react-native.

Not only easier and type safe, but also zero-cost (with the new ReasonReact / [@react.component])!

**Comment by MoOx** [comment]
Ok so we will keep this solution.
