### ISSUE TITLE
Enable GitHub projects so we can track the roadmap

### ISSUE THREAD

**Issue by grsabreu** [reasonml-community/bs-react-native#348]
Suggestion to start using GitHub projects so everyone can see more clearly what's the roadmap

**Comment by MoOx** [comment]
I will try to take some time to do that.
Basically the current plan is to create new bindings, more straight forward, with zero-cost runtime (js files produced for bindings should be basically empty.
This means less "pure" things, but more accessible for new comers & easy to maintain.

**Comment by MoOx** [comment]
I started https://github.com/reasonml-community/bs-react-native/projects/1
Feel free to comment, ask questions, open issue etc. Help is always welcome :)
