### ISSUE TITLE
git-monorepo-usage-trick dies in CI only

### ISSUE THREAD

**Issue by maxkorp** [reasonml-community/bs-react-native#358]
Hi guys,
We're using the latest of this inside of our own monorepo which has our mobile app, a webpage, an api server, and other stuff. To get the mobile app to play nice we did have to update from the latest published version to the repo version, and so we tacked the monorepo trick into our bsconfig. Locally, this works great. In CI however, it dies, because none of the files are present at the time it runs, but they are after `bsb -make-world` is complete.

I tried sleeping first inside the trick (I pulled the script out locally to be able to run a modified version)

```bash
if [ ! -f $1 ]; then
    echo "File not found: $1"
    sleep 1
fi

if [ ! -f $1 ]; then
    echo "File still not found: $1"
    sleep 5
fi

if [ ! -f $1 ]; then
    echo "File still not found, but avoiding errors: $1"
fi

sed -i '' -e 's/require("bs-react-native\//require("bs-react-native\/bs-react-native\//g' $1 || echo ""
sed -i '' -e 's/from "bs-react-native\//from "bs-react-native\/bs-react-native\//g' $1 || echo ""
```

However, it appears that the file is never present until the hook runs. 

We've resorted to a fork of the trick that doesn't run in CI, and instead when we're in CI we run it on all .bs.js files when `-make-world` completes. 

We are running with a custom build agent inside gitlab, based on the node10.15 image. I've tried loading that image into docker locally, and cloned the repo and ran the build, and it was successful. Not entirely sure if this is actually a bs-react-native issue vs a bs-platform issue, so I can file this over there if that's more appropriate.

**Comment by maxkorp** [comment]
Update: the file exists, but is somehow not a regular file. I suspect the gitlab runner has the build directory mounted as a docker volume or something which is causing the files to be... irregular. Reading them and writing them with node rather than sed -i fixes it. 

Pretty sure this is an issue with our build process, but in case anybody else bumps in to this (or if you guys want to make the script more robust), here's what we ended up with for the js-post-build hook

```js
#!/usr/bin/env node
const fs = require('fs');

const file = process.argv[2];

const guts = fs.readFileSync(file)
  .toString()
  .replace(/require\("bs-react-native\//g, 'require("bs-react-native/bs-react-native/')
  .replace(/from "bs-react-native\//g, 'from "bs-react-native/bs-react-native/');

fs.writeFileSync(file, guts);
```

**Comment by MoOx** [comment]
I would try to provide node version for windows compat.
