### ISSUE TITLE
Zero-cost bindings to WebView

### ISSUE THREAD

**Issue by sgny** [reasonml-community/bs-react-native#392]
Work in progress

**Comment by MoOx** [comment]
Are we sure we want bindings for deprecated stuff? (me think).
This will be moved out of the core at the end. We could still move this to additional packages as soon as they are removed from core tho

**Comment by sgny** [comment]
I would like to use these bindings, so I will work on them anyway. I read #331 to mean we would have repos for bindings to components extracted from the core, but I suppose that's not settled yet.

I'll refrain from creating a PR for this until that broader issue is decided upon.

**Comment by cknitt** [comment]
Aaargh, sorry, didn't see that one and had already started work on WebView, too, yesterday morning. 😕

We should list the components still to do in #344 or somewhere and note there who is working on what.

Sorry again!

**Comment by cknitt** [comment]
(See #396 for my PR.)

**Comment by cknitt** [comment]
In any case, I think it is good to have bindings for the deprecated stuff around until it's really removed from React Native.

(And the API of react-native-webview is pretty much identical anyway, so we can reuse most of the work there.)

**Comment by MoOx** [comment]
We already have a list of non implemented stuff on the sidebar here https://reasonml-community.github.io/bs-react-native/en/docs/
So from now on, we should just open an issue when we start working on something to avoid wasting your time :D 

Closes by 777f22a

**Comment by cknitt** [comment]
You are right. I should have created an issue yesterday morning when I started to work on WebView.

I also have some work in progress for NetInfo and CameraRoll lying around - will create issues to claim those.
