### ISSUE TITLE
requestAnimationFrame/cancelAnimationFrame: where to put this bindings?

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#393]
It's a simple one, but would be nice to have it around.

https://facebook.github.io/react-native/docs/timers#timers

```reason
type requestID;

[@bs.val] external requestAnimationFrame : (unit => unit) => requestID = "requestAnimationFrame";
[@bs.val] external cancelAnimationFrame : requestID => unit = "cancelAnimationFrame";
```

Do you think we should create a Timer module? Idea for better name?

We could go for `AnimationFrame` and do `AnimationFrame.request` & `cancel` (I like this) but this will make discoverability hard for new comers (well even with Timer or something else that won't be straight foward...)

**Comment by MoOx** [comment]
We could go for this (even if verbose)

```reason
module AnimationFrame = {
  type requestID;

  [@bs.val]
  external requestAnimationFrame: (unit => unit) => requestID =
    "requestAnimationFrame";
  [@bs.val]
  external cancelAnimationFrame: requestID => unit = "cancelAnimationFrame";
};
```

**Comment by sgny** [comment]
Why not add it to the `Animation` module? It's not exactly the same thing as starting or stopping the animation, but to me at least it's the analogue of having a play frame-by-frame button in a media player (which runs functions).

I see there are also `forkEvent`, `unforkEvent` and `LayoutAnimation` that have not been added yet, I'll try to get them in as well.

**Comment by cknitt** [comment]
I am leaning towards a separate module as these are not part of React Native's `Animated` API but rather standard web api functions.

They are available in bs-webapi (but it probably does not make sense to include bs-webapi in a ReactNative app): https://github.com/reasonml-community/bs-webapi-incubator/blob/master/src/Webapi.re

`Timers` (or maybe even `Webapi`?) sounds good to me.

**Comment by MoOx** [comment]
Just had the idea of making a `Global` module to include this kind of thing. What do you think about it?

**Comment by cknitt** [comment]
Also fine with me!
