### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by kennetpostigo** [reasonml-community/bs-react-native#41]
What is the recommended navigation strategy when using bs-react-native?

**Comment by saschatimme** [comment]
I think it's fair to say, that navigation is a mess in react-native.
There is https://github.com/saschatimme/bs-react-navigation with bindings to [react-navigation](https://reactnavigation.org). They cover currently StackNavigator and TabNavigator which should suffice for most things. But I didn't have time so far to polish things and I wrote the bindings for `v1.0.0-beta.9` so I think some small things are missing (new version is `v1.0.0-beta.11`).

If you target iOS only, we could make bindings to `NavigatorIOS` which has a smaller API surface than most other routers (but is also kinda buggy...).

I think @wokalski plans to start a new RN app soon, maybe you could cooperate to polish one solution :)

**Comment by wokalski** [comment]
Yes, I don't know what I'll be using, probably `bs-react-navigation` with another API.

**Comment by kennetpostigo** [comment]
Awesome, I'll probably help use bs-react-navigation in this case.

**Comment by saschatimme** [comment]
`bs-react-navigation` is currently only for the old ReasonReact version. I started to update it but got it only half finished (`StackNavigator` works). So if somebody wants to pick that up, get in touch :)

**Comment by arnarthor** [comment]
Really late answer, but we're using `react-router` where I work and love it. It does require you to create your own route animations though.

**Comment by wokalski** [comment]
Closing this one. There's `react-router` and `reason-react-native-navigation`. Still no winner but a little bird told me it might change.
