### ISSUE TITLE
More granular style for Image/Text etc?

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#436]
While working on #413 I found that ImageBackground accept style & imageStyle, which aren't currently typed the same in new bindings.

But both are the same (even if RN doc on the website is confusing about it) => https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheetTypes.js#L621-L626

Do you think we should do like RN is doing with flow more strong check on styles props depending on what element is that?

@cknitt @sgny Do you think we should (& can easily) replicate this ViewStyle, TextStyle, ImageStyle without too much pain?

**Comment by MoOx** [comment]
In practice, this is wrong as incomplete https://github.com/reasonml-community/bs-react-native/blob/b4221e08410e47b09c4298a99b993420b8c4f3d9/reason-react-native/src/components/ImageBackground.re#L6-L33

**Comment by sgny** [comment]
It should not be too much pain, as we could simply add all the missing keys to `imageStyle` or `textStyle`, etc. Not much different than adding `View` props to all components.

We should check implementations of the components, however, perhaps any missing props are meant to be inherited from the parent?

**Comment by cknitt** [comment]
So you mean that we would then have in `Style.re`:

```re
type viewStyle;
[@bs.obj]
external viewStyle: ( ... /* view style props */ ) => viewStyle = "";

type textStyle;
[@bs.obj]
external textStyle: ( ... /* text style props */ ) => textStyle = "";

// etc.
```

?

This will be hard to use because the user would need to remember the correct type of style object to create for each use case.

**Comment by MoOx** [comment]
Sure this will be a bit harder to use, but would avoid a thing that people do often: add a text color on a view (that's just an example).

We could imagining having, like ref, a style in each component (which will be an alias for the appropriate style).

`<ImageBackground style=ImageBackground.style() imageStyle=Image.style() />`

Probably too much verbose tho. 

Currently we would have

- layoutStyle (private)
- transformStyle (private)
- shadowStyle (private)
- viewStyle
- textStyle
- imageStyle

No sure if a dangerous/unsafe way is smart, but we could allow it.

See https://github.com/facebook/react-native/blob/54af7fc64515cf5dd2d6409eaf8d6292a814b039/Libraries/StyleSheet/StyleSheetTypes.js#L643-L658

**Comment by sgny** [comment]
We could also define a separate type for each group of props. According to that code reference, most types are simply defined to be composites of simpler type. For example going by that, we could have 

`layoutStyle` => `margin*`, `padding*`, etc.
`textStyle` => `fontSize`, `fontFamily`, etc.
`shadowProps` => ..
`viewProps` => ...

and then for each component we would have a `style` type and define functions that convert each type above to `style`. We could then pass an array of `styles` to the `style` prop of the component as below.

```
style=[|fromLayout(..), fromShadow(..), fromView(..)|]
```
Admittedly, this might be a bit too painful.

A simplification on this might be to take this kind of measure only for components that take text style props. We'd remove all those props from the `Style.style` constructor and define a `Style.textStyle` constructor. Then, for such components we'd have
```
style=[|fromText(someTextStyle), someStyle |]
```

We have many difficulties with these props as you already know many are iOS or Android only and some are advised to be set in conjunction. We could define `iOSStyle`, `androidStyle` and `sharedStyle` and compose them and make use of `Platform.select`. This would bring significant benefits, but at a significant cost. 

It would also be nice to preclude Animated values as values for style props from non-Animated components, but that would require a distinct make function for each such component instead of piggybacking off of the simple components (#417 instead of #418).

**Comment by MoOx** [comment]
For end users, we should only focus on imo the 3 public different styles: view, text & image.
We should not try to block things depending on the platform as it make is hard to use for other platform (more & more people are using bs-react-native on the web, including me).

Like for #440, we could imagine `including` stuff so people could just write `<Text style=Text.(style(...)) />`

StyleSheet might look like

```reason
let styles = StyleSheet.create({
  "view": View.(style(~height=....)),
  "text": Text.(style(~height=....)),
  "image": Image.(style(~height=....)),
})
```

**Comment by sgny** [comment]
If we have separate `textStyle` `imageStyle`, etc. as in the JS API, we don't even need to include modules and could refer to `Style.textStyle`, `Style.imageStyle`, etc. in constructors of each component.

If we have types for groups of props defined in separate modules, we could include only modules defining allowed props for each component.

So for `Image` we'd have
```
type style;
...
include Style.View({type t = style;})
include Style.Image({type t = style;})
```
but for `Text` we'd have
```
type style
...
include Style.View({type t = style;})
include Style.Text({type t = style;})
```
and then pass an `array(style)` either directly or converted to `style` as already defined in `Style.array`.

Then within `Style.View` we could either have one `style` constructor or separate `iOSStyle`, `androidStyle`, `webStyle` and `commonStyle` constructors. I will readily grant you that the latter may be too complicated.

**Comment by MoOx** [comment]
I think we should keep things simple & go for `Style.style` that allow ALL & do more refined method like `Style.viewStyle`, `Style.textStyle` & `Style.imageStyle`. This way, it's not a pain to use but we could document this more clearly & advise people to use Style.*Style method.

**Comment by sgny** [comment]
So we'd have type `t` in `Style` and multiple constructors for it: `imageStyle`, `textStyle`, `viewStyle` in addition to `style` already in place. `imageStyle` and `textStyle` would be supersets of `viewStyle` - `style` is not getting partitioned.

Then, with any component that's not `Image`, `Text` or `TextInput` one should ideally use the `viewStyle` constructor. To be honest, I have never used most of those props, so I'm not very certain if there are pitfalls beyond that.

If this is an accurate picture, that seems like a fairly painless transition.

**Comment by MoOx** [comment]
I only see that as an additional way to secure your code.** Anyway, RN is doing a runtime check & blow to your face if you send a `color` text style to a view.**

_If we want to ensure securely that we don't send a color to a view, we will have to end up with something probably painful as we will have to validate stylesheet etc (& this will clearly be a nightmare, for us & end users)._ I don't think that's a good idea to do that atm as it will require a new api on top of the current bindings to secure this.

I am just going to repeat myself: I see those `Style.*Style` additions as a way to add another additional OPTIONAL layer to avoid RN blowing up in your face. This won't avoid people doing mistakes tho as if those things all return `Style.t` we cannot verify anything. I guess someday I will use those method wrong.

We could decide to just forget about this idea & let RN blow to our face. I opened this issue in the first place cause I found that ImageBackground expect an imageStyle to be just style for an image (it's really not clear in their doc)...

**Comment by sgny** [comment]
> I am just going to repeat myself: I see those `Style.*Style` additions as a way to add another additional OPTIONAL layer to avoid RN blowing up in your face. This won't avoid people doing mistakes tho as if those things all return `Style.t` we cannot verify anything. I guess someday I will use those method wrong.

This makes being disciplined about the matter easier, so I'd appreciate having the safety net. If I discipline myself to use `viewStyle` for most components and make use of `imageStyle` and `textStyle` only when called for, that should reduce the number of times RN blows up. We're building on fairly fluid foundations. When I see all those dependencies in my `node_modules` folder, I despair at times!

> We could decide to just forget about this idea & let RN blow to our face. I opened this issue in the first place cause I found that ImageBackground expect an imageStyle to be just style for an image (it's really not clear in their doc)...

I certainly appreciated the discussion and thinking about the problem My apologies, if I caused you to have another impression, that certainly was not intended.

**Comment by MoOx** [comment]
> I certainly appreciated the discussion and thinking about the problem My apologies, if I caused you to have another impression, that certainly was not intended.

No worries, I am just thinking out loud 😄

I also appreciate the time we spend here, to think on improving the "situation" ! 👍

@cknitt any thoughts on recent comments?

**Comment by cknitt** [comment]
> I think we should keep things simple & go for `Style.style` that allow ALL & do more refined method like `Style.viewStyle`, `Style.textStyle` & `Style.imageStyle`. This way, it's not a pain to use but we could document this more clearly & advise people to use Style.*Style method.

@MoOx This approach is fine with me. Will you come up with a PR? (I will be finishing #440 and #428 next.)

**Comment by MoOx** [comment]
@cknitt Yeah I can do that. I am finishing #413 and will do that right after.

**Comment by MoOx** [comment]
I am on it as well as a clean doc for styles apis.
