### ISSUE TITLE
Installing using git url

### ISSUE THREAD

**Issue by fakenickels** [reasonml-community/bs-react-native#469]
As per the documentation it says to use `bs-react-native` namespace to refer to the git installation
```
{
  // ...
  "bs-dependencies": [
    // BsReactNative, current "stable" bindings
    "bs-react-native/bs-react-native",
    // ReactNative, WIP on zero-cost bindings (require bs-platform 5.0.0 & and reason-react hooks branch)
    "bs-react-native/reason-react-native"
  },
  // When used from git with the following path, bs-platform will use path that won't be working
  // (because deps are pointing to folder in folder)`
  // Your bundler (metro or webpack) will say that it can find `bs-react-native/whatever` and/or
  // `reason-react-native/whatever`
  // which is correct because it should be `bs-react-native/bs-react-native/whatever` / `bs-react-native/reason-react-native/whatever`
  // the trick below will correct path in generated JavaScript files
  // and will just need to be removed when you won't use git directly anymore
  "js-post-build": {
    "cmd": "./node_modules/bs-react-native/git-monorepo-usage-trick"
  }
}
```

where when installing with yarn the destination is actually `node_modules/bs-react-native-monorepo` so I gotta do a `mv` to rename properly. I'm not sure if I'm doing something wrong or the docs are misleading.

Let me know if I can send a PR for this!

**Comment by MoOx** [comment]
Can you show your package.json line which specify the git monorepo?

**Comment by fakenickels** [comment]
ofc!
when I do 
```
yarn add https://github.com/reasonml-community/bs-react-native.git
```
it outputs
```json
"dependencies": {
     ...
    "bs-react-native-monorepo": "https://github.com/reasonml-community/bs-react-native.git",
}
```

**Comment by MoOx** [comment]
Ohh, I see...

Just remove `-monorepo` from the package name on the key of the dep. Let me know if that works.

**Comment by fakenickels** [comment]
Ah, I think you guys must be testing within the monorepo itself right? So that's why we get this difference

**Comment by MoOx** [comment]
Not really, I usually add git deps by hand in the package.json 😄 
We should fix that somehow.

**Comment by fakenickels** [comment]
aah got it haha makes sense
I think renaming the root package.json `name` property to `bs-react-native` would do the trick!
Either that or updating the git-monorepo-trick fix and the steps to include the monorepo suffix

**Comment by fakenickels** [comment]
```diff
"dependencies": {
     ...
-    "bs-react-native-monorepo": "https://github.com/reasonml-community/bs-react-native.git",
+    "bs-react-native": "https://github.com/reasonml-community/bs-react-native.git",
}
```

This worked, thank you!

**Comment by MoOx** [comment]
Will close when fixed :)

**Comment by fakenickels** [comment]
Indeed! Went too fast there haha.
I can send the PR renaming the package.json root name to bs-react-native, I think that should be enough.
