### ISSUE TITLE
UIManager

### ISSUE THREAD

**Issue by sgny** [reasonml-community/bs-react-native#483]
On Android, using LayoutAnimation requires enabling it as below: 
```
UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);
```
This seems rather unusual, but the method is meant to be removed once `LayoutAnimation` is no longer experimental on Android. To avoid runtime errors, it is prudent to check for its presence beforehand, hence the method is called wrapped in a conditional.

While exploring this, I noticed some undocumented methods (such as popups!) for which I have started defining bindings. I will complete what I can and create a PR.

**Comment by MoOx** [comment]
Closed by #496
