### ISSUE TITLE
Remove Types module

### ISSUE THREAD

**Issue by cknitt** [reasonml-community/bs-react-native#486]
@MoOx I think we should remove the `Types` module before a release. It only contains two abstract types, `edgeInsets` and `point`, and there is a high chance it will conflict with a `Types` module in your project if you do `open ReactNative;`.

* `point` is only used for the `contentOffset` prop in `ScrollView` + subclasses and could therefore be declared in the `ScrollView` module. (Maybe it should be renamed to `contentOffset`, too?)
* `edgeInsets` is only used for some props in `View` + subclasses and could therefore be declared in the `View` module.

Alternatively, if we don't go that way, we could rename `Types` to `ViewPropTypes` instead.

**Comment by MoOx** [comment]
I totally dislike generic name indeed.
Both solutions works for me, I would go to have something that require less maintenance & that's more obvious.
Moving things into proper module make sense. Not sure `ViewPropTypes` is a good idea as this will not match RN `ViewPropTypes` at all.

**Comment by cknitt** [comment]
Ok, so I'll prepare a PR for `View.edgeInsets` and `ScrollView.contentOffset` later today or tomorrow. I think these are more obvious?

**Comment by wokalski** [comment]
I agree @cknitt

**Comment by MoOx** [comment]
Yeah looks good

**Comment by sgny** [comment]
I won't erase the above comment, but upon further testing in the simulator, everything seems to work fine.

I tested the build locally, and posted when that went without errors. Then, I wanted to make sure that the later definition did not in fact replace the earlier one. So, I tried that bit out on `Try Reason` (because I did not want to start the simulator) and it didn't work at all and I commented as above.

**Comment by sgny** [comment]
Upon further testing, my suggestion only seems to have issues on `Try Reason` because of an already known issue (see the note on `foo##bar`); it's perfectly fine as tested on the simulator.

**Comment by sgny** [comment]
I made the mistake of testing on `Try Reason` as I forgot the issue with `##` accessors. First I posted a followup, that my code did not actually work, then posted again saying it does after I tested on the simulator.

For some reason, my later posts did not show up (apparently my first post is timestamped five hours *in the future*). Sorry about the duplicate posts (now deleted).

**Comment by cknitt** [comment]
In keeping with https://github.com/reasonml-community/bs-react-native/blob/master/reason-react-native/CONTRIBUTING.md, I'd rather keep different types (abstract types for View props, Js.t types for events/callback params).

I have created PR #488 with the changes I suggested.

**Comment by cknitt** [comment]
@sgny I have merged my PR now to get rid of the `Types` module, sorry for not addressing your comments.

If we made a `ContentOffset` module, then the user would need to use `ContentOffset.contentOffset` to create an instance, or maybe `ContentOffset.t`. Both feel a bit weird IMHO.

**Comment by MoOx** [comment]
`ContentOffset.t` is better than `ContentOffset.contentOffset`.
I think we should not be afraid to have redundant types as soon as they are not explicitely the same (in this case that's more probably because inheritance, so no big deal to use ScrollView.something in VirtualizedList for example)

**Comment by sgny** [comment]
@cknitt That's alright. I don't contest that `ContentOffset.t` is a bit ugly - perhaps `create` or `make` would have been better - but anyway, that's settled already.

@MoOx They are actually the same type, since `contentOffset` and `contentInset` are keys in `Event.scrollEvent` and we need accessors in a callback and accordingly `Js.t` definition.

How about we add the equivalent `Js.t` type to `ScrollView` and revise `Event` to refer to that type instead?

**Comment by MoOx** [comment]
@sgny you last edits make sense :)

**Comment by MoOx** [comment]
Can we close this issue?

**Comment by sgny** [comment]
@MoOx @cknitt Should I revise `Event` as I proposed or not?

**Comment by cknitt** [comment]
Using `ScrollViewElement.contentOffset` also feels a bit weird IMHO.

I think we should better revisit this after the release (and some feedback from others users). So from my point of view, this issue can be closed, and we should open a new one later when we want to revisit this.

**Comment by sgny** [comment]
> Using `ScrollViewElement.contentOffset` also feels a bit weird IMHO.
> 
> I think we should better revisit this after the release (and some feedback from others users). So from my point of view, this issue can be closed, and we should open a new one later when we want to revisit this.

Just as with `element` (`FlatList.element`, etc.), we'd have `FlatList.contentOffset` etc.

**Comment by MoOx** [comment]
We can revisit this later.
