### ISSUE TITLE
Transform module changes

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#503]
I am just starting to really play with new bindings, & I think Transform need some changes:

- `Transform.translateY(~translateY=VALUE, ())` is really verbose (same for others). Why are we using named args when the name of the function make it obvious ?
- I didn't find how to use an animated value with Transform. I am converting some old code & it seems that all `Transform.{method}` only accept specific types. So we should create abstract types or add new animated method so we can pass animated values (or make unsafe magic method).
- Also, `Transform` module should be `Style_Transform` & aliased in `Style.Transform`

I may add other comments or directly open PR to improve the situation.
Comments/ideas welcome :)

**Comment by MoOx** [comment]
> Transform.translateY(~translateY=VALUE, ()) is really verbose (same for others). Why are we using named args when the name of the function make it obvious ?

Got it, that's because RN expect object with a single key. I wish we could find something better for the API. Maybe a not so zero-cost solution?

**Comment by MoOx** [comment]
> I didn't find how to use an animated value with Transform. I am converting some old code & it seems that all Transform.{method} only accept specific types. So we should create abstract types or add new animated method so we can pass animated values (or make unsafe magic method).

Would this be ok?

```reason
external animatedFloat: Animated.value('a) => float = "%identity";
external animatedAngle: Animated.value('a) => angle = "%identity";
```

(to add in Transform module or in Animated?)

**Comment by sgny** [comment]
We already have the `animatedStyle` super magic method that converts `value('a)` to any type, to be able to pass an animated value to any style prop. We could be more precise and add regular magic methods to convert to `float`, `size`, `margin`, etc.

On the other hand, it is not recommended to get the current value of an animation directly over JS

From RN documentation on [Animations](https://facebook.github.io/react-native/docs/animations):
> Responding to the current animation value

You may notice that there is no obvious way to read the current value while animating. This is because the value may only be known in the native runtime due to optimizations. If you need to run JavaScript in response to the current value, there are two approaches:

spring.stopAnimation(callback) will stop the animation and invoke callback with the final value. This is useful when making gesture transitions.
spring.addListener(callback) will invoke callback asynchronously while the animation is running, providing a recent value. This is useful for triggering state changes, for example snapping a bobble to a new option as the user drags it closer, because these larger state changes are less sensitive to a few frames of lag compared to continuous gestures like panning which need to run at 60 fps.
Animated is designed to be fully serializable so that animations can be run in a high performance way, independent of the normal JavaScript event loop. This does influence the API, so keep that in mind when it seems a little trickier to do something compared to a fully synchronous system. Check out Animated.Value.addListener as a way to work around some of these limitations, but use it sparingly since it might have performance implications in the future.

**Comment by MoOx** [comment]
> On the other hand, it is not recommended to get the current value of an animation directly over JS

This doesn't seems relevant in the case I have in mind.
If you have a transformation with a translateY interpolated & something else (eg: scale) static, you NEED this helpers to say "this is an animatedFloat, just take it as a float".

Here is what I am doing here (a Sticky component)

```reason
open ReactNative;

external animatedFloat: Animated.value('a) => float = "%identity";

let make = (~scrollYAnimatedValue, ~children) => {
  <Animated.View
    style=Style.(
      style(
        ~zIndex=1,
        ~transform=
          Transform.(
            [|
              translateY(
                ~translateY=
                  Animated.Interpolation.(
                    scrollYAnimatedValue->interpolate(
                      config(
                        ~inputRange=[|0., 1.|],
                        ~outputRange=[|0., 1.|]->fromFloatArray,
                        ~extrapolateLeft=`clamp,
                        ~extrapolate=`identity,
                        ~extrapolateRight=`identity,
                        (),
                      ),
                    )
                  )
                  ->animatedFloat,
              ),
            |]
          ),
        (),
      )
    )>
    ...children
  </Animated.View>;
};
```

If I need (I won't here but...) another static value, like I said scale or whatever, `animatedStyle` isn't enough.

**Comment by MoOx** [comment]
Btw, I think I would also just move Transform method into Style directly, for commodity. 
All transform method only make sense in styles definition anyway, so having to `open Transform` or `Transform.(` is just an unnecessary extra step imo.

**Comment by sgny** [comment]
> > On the other hand, it is not recommended to get the current value of an animation directly over JS
> 
> This doesn't seems relevant in the case I have in mind.
> If you have a transformation with a translateY interpolated & something else (eg: scale) static, you NEED this helpers to say "this is an animatedFloat, just take it as a float".

Sure, I realise that your intended use case poses no risk, but a disclaimer in documentation would be useful in case people saw `Animated.value('a) => float` and got ideas.

> If I need (I won't here but...) another static value, like I said scale or whatever, `animatedStyle` isn't enough.

I haven't run into problems using `animatedStyle` to pass `Animated` values as `Style.size` and `float` within the same `style` definition, but I have nothing against more precise functions.

**Comment by MoOx** [comment]
> so I presume
your suggestion is to move all functions out of Transform, directly into Style, then

Yes :)

Going to make a PR for that & that would be more clear for everyone.

note: `animatedStyle` works if you have opacity or whatever is a style. But for transform properties (transform is a style by itself & accept Transform.t, not Style.t) we need those additional magic method otherwise it's just impossible to make the compilation pass.

**Comment by sgny** [comment]
In the new bindings, we don't really have methods returning `Style.t`, I use `animatedStyle` to pass the animated value as a float, just as you do with `animatedFloat`. My code is pretty much the same as what you have, 

```
~transform= [|
                Transform.scale(
                  ~scale=Animated.animatedStyle(
                    Animated.Interpolation.interpolate(
                      cardAnimation,
                      Animated.Interpolation.config(
                        ~inputRange=[|0., 1.|],
                        ~outputRange=Animated.Interpolation.fromFloatArray([|0.5, 1.|]),
                        ()
                      )
                    )
                  )
                )
              |],
```
(maybe I should make use of local opens a bit more)

**Comment by MoOx** [comment]
Oh I see. Didn't saw that animatedStyle returned `'b` I was thinking it was `Style.t`...

Maybe we should have

```reason
external animatedStyle: value('a) => Style.t = "%identity";
external animatedFloat: value('a) => float = "%identity";
external animatedAngle: value('a) => angle = "%identity";
```

?

**Comment by sgny** [comment]
> Oh I see. Didn't saw that animatedStyle returned `'b` I was thinking it was `Style.t`...
> 
> Maybe we should have
> 
> ```reason
> external animatedStyle: value('a) => Style.t = "%identity";
> external animatedFloat: value('a) => float = "%identity";
> external animatedAngle: value('a) => angle = "%identity";
> ```
> 
> ?

I'd add
```reason
external animatedSize: value('a) => size = "%identity";
external animatedMargin: value('a) => margin = "%identity";
external animatedColor: value('a) => Color.t = "%identity";
```
(perhaps `animatedMargin` is not necessary as `type margin=size`) and exclude
```reason
external animatedStyle: value('a) => Style.t = "%identity";
```
because that would cause errors wherever `Style.t` can be passed, or at least I can't think of any scenario where it would work.

**Comment by MoOx** [comment]
Yeah right!

**Comment by sgny** [comment]
@MoOx I realized that `Color.t` and `angle` require appropriate interpolations with string arrays to define `outputRange', such as `[|"0deg", "360deg"|]`. For some added type safety, I figured `animatedColor` and `animatedAngle` should only accept `value(calculated)` and prepared #508 to capture this.
