### ISSUE TITLE
Extract commonly used types

### ISSUE THREAD

**Issue by saschatimme** [reasonml-community/bs-react-native#51]
One example would be `ImageRe.Image.imageSource`. Every component which would support images would need this type. This also doesn't only affect the RN core components but also third party components.
I ran in a similar issue as I ported `react-native-vector-icons` since there you create a component which extends `Text`, so you would need to copy all the stuff from `TextRe` to bind it properly.

**Comment by wokalski** [comment]
I think this should be considered resolved especially given the existing functors. Please reopen if necessary cc @MoOx
