### ISSUE TITLE
Should Dimensions.get return floats?

### ISSUE THREAD

**Issue by cknitt** [reasonml-community/bs-react-native#522]
While reviewing the docs, I noticed this pattern:

```reason
let windowHeight = Dimensions.get(`window)##height->float_of_int;
let windowWidth = Dimensions.get(`window)##width->float_of_int;
```

I guess we should just change `Dimensions.get` to return floats instead of ints? @MoOx @sgny

**Comment by MoOx** [comment]
I would say yes, as very few places use int compared to float.

**Comment by sgny** [comment]
I think so, I don't see much use to keeping the values as `int` - even if they actually are - because one would always needs some fraction of it.

I'm creating a PR, if that's agreed then.
