### ISSUE TITLE
Replace Style.pt with Style.px

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#530]
RN doc never mention point, but instead "density-independent pixels", also know as "logical pixels".
I guess we used `pt` because previous bindings where using `Pt`? 
Also I am proposing this because `pt` vs `pct` is harder to differentiate with `px` vs `pct`.

Thoughts @cknitt @sgny ?

**Comment by sgny** [comment]
Sounds good to me

**Comment by cknitt** [comment]
Agreed, "point" does not actually make much sense.

In https://facebook.github.io/react-native/docs/pixelratio.html#content they are talking about

* layout size (dp) vs.
* device pixel size (px)

dp or dip = Density-independent Pixel, see

* https://stackoverflow.com/questions/34493372/what-is-the-default-unit-of-style-in-react-native
* https://developer.android.com/guide/practices/screens_support.html#density-independence

So I guess `dp` would actually be correct...

**Comment by MoOx** [comment]
poke @cpojer: I think you can be interested to know that this point is totally not explicit in RN docs. Imo this should be explained in "Style" guide at the beginning, or in "width & height" page...
