### ISSUE TITLE
Add CI for RNTester

### ISSUE THREAD

**Issue by saschatimme** [reasonml-community/bs-react-native#54]
Currently the RNTester app is not tested, since I'm not sure how to setup everything.

Would be appreciated if someone with a little bit travis-ci foo could help out :)

**Comment by arnarthor** [comment]
We're using Lerna internally at my company with a React Native app and then a Reason web and it works fine in Travis. I could take a look at this sometime soon if no one else grabs it before me.

**Comment by arnarthor** [comment]
Or we could check this out for monorepo structure https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/

**Comment by saschatimme** [comment]
One issue is probably that the RN package [doesn't support symlinks](https://github.com/facebook/metro-bundler/issues/1) 😞

**Comment by wokalski** [comment]
Fixed by #143
