### ISSUE TITLE
Enable Namespaces

### ISSUE THREAD

**Issue by saschatimme** [reasonml-community/bs-react-native#60]
Now that namespaces landed, we should enable it :)

**Comment by wokalski** [comment]
The question is if the name of the namespace should be `BsReactNative` or `ReactNative` (as it is now). I'd like it to be `ReactNative` and it is technically possible but I'm not sure what's better.

**Comment by lpalmes** [comment]
I had the same problem with my bindings to material-ui, i had named them `material-ui ` in my bsconfig.json so it would be accessible as `open MaterialUi;`, but then it looks for the bindings in `require("material-ui/src/buttons.js")` and it failed.

So i had to change it to `bs-material-ui` so it can properly look in `bs-material-ui/src/button.js`

**Comment by nhducit** [comment]
https://github.com/reasonml-community/bs-react-native/releases

**Comment by wokalski** [comment]
@nhducit right! Thank you!
