### ISSUE TITLE
bs-react-native components fail to build

### ISSUE THREAD

**Issue by kliron** [reasonml-community/bs-react-native#67]
I have created a react native app skeleton with `create-react-native-app` and followed the instructions of the bs-react-native Readme to set up the reason toolchain. 
When I execute `yarn watch` for the first time the compilation of 2 components fails with:

FAILED: src/components/viewRe.cmi
[...]
File "/Users/kliron/Projects/my_app/node_modules/bs-react-native/src/components/viewRe.rei", line 44, characters 4-75:
Error: The type constructor ReasonReact.component expects 3 argument(s),
       but is here applied to 2 argument(s)

I get the same error for modalRe.rei

**Comment by wokalski** [comment]
I think you're using an outdated version of `bs-react-native`. Please use the one from master for now.

@saschatimme could you cut a new release with all the changes up to now?
