### ISSUE TITLE
Should reason-react be a peer dependency?

### ISSUE THREAD

**Issue by arnarthor** [reasonml-community/bs-react-native#82]
Shouldn't reason-react be specified as a peer dependency instead of dependency of this project. 

We've encountered bugs in our project where multiple projects where depending on bs-json and when pattern matching on errors that the project throws when decoding errors occur.

**Comment by wokalski** [comment]
hm, yes it probably should. I remember a discussion from discord about it but can't recall what was the conclusion. Could you ask there to verify?

**Comment by wokalski** [comment]
But it's a fact that you don't want duplicated packages. `bsb` picks only one and in general is not too predictable in such scenario.

**Comment by gunnigylfa** [comment]
IMO it should not be a peer dependency because of the Duplicate package problem with `bsb`.

**Comment by arnarthor** [comment]
By having this as a peer dependency that would be solved since each project would be required to install reason-react individually but not have all the different packages install it's own version of reason-react.

Having packages as dependencies is generally a bad idea because the compiler can't deal with multiple conflicting versions

**Comment by arnarthor** [comment]
![image](https://user-images.githubusercontent.com/4514159/32983011-deecfbd4-cc85-11e7-9b28-fa63cce76d50.png)
See this discussion on discord for more context @gunnigylfa

**Comment by gunnigylfa** [comment]
My bad, I thought my project was running into the duplicate project because of the peer dep. But it's  exactly the opposite we are experiencing this problem because it's a dependency and we are refering to an old version of this package.

**Comment by arnarthor** [comment]
This will be fixed in the next release
