### ISSUE TITLE
Treat warnings as errors on CircleCI

### ISSUE THREAD

**Issue by wokalski** [reasonml-community/bs-react-native#85]
We need to set `-warn-error` in the `bucklescript` flags. Additionally we might consider adding `@A` which turns on all warnings and makes them errors.

**Comment by grabbou** [comment]
Updated description to better reflect current CI. Good first task.

**Comment by MoOx** [comment]
I guess #277 closed this, so I am closing this issue. Feel free to reopen if I did something wrong :)
