### ISSUE TITLE
Replace hand-typed js<->record converters with BS generated ones

### ISSUE THREAD

**Issue by wokalski** [reasonml-community/bs-react-native#95]
There are multiple functions which convert between JS objects and records in the codebase. Thanks to the [new feature](https://bucklescript.github.io/bucklescript/Manual.html#_mapping_between_js_values_and_ocaml_values_since_2_1_0) they can be removed.

**Comment by wokalski** [comment]
I meant objects rather than the variants.

**Comment by mobily** [comment]
![picard-facepalm-2](https://user-images.githubusercontent.com/1467712/37990877-d22b2334-3207-11e8-9cae-85c8157bf03e.jpg)

sorry, misreading 😉 anyway, I still want to do that :)

**Comment by MoOx** [comment]
I am going to take care of this.
I can easily migrate polymorphic variants. But for normal variant, bs can't help as it's converting to int.
I am still new to reason so here is a noob question: should we use polymorphic variants everywhere?

**Comment by wokalski** [comment]
IMO it's best to use normal variants everywhere (unless there's a good reason to have row polymorphism). Normal variants provide better error messages.

**Comment by MoOx** [comment]
So I understand we should better stop using polymorphic variants & generated bs strings helpers (so we should close this issue?)

**Comment by MoOx** [comment]
I am curious to understand why in the first place polymorphic variants where used (a lot) :)

**Comment by MoOx** [comment]
Next version should be more than ok about this issue
